# This workflow will build a Java project with Gradle   #
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: Java CI with Gradle and Docker

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build-and-push:

    runs-on: ubuntu-latest
    
    steps:
      # 1️⃣ Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2️⃣ Set up JDK 1.8
      - name: Set up JDK 1.8
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 1.8

      # 3️⃣ Grant execute permission for Gradle wrapper
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      # 4️⃣ Build the Java project with Gradle
      - name: Build with Gradle
        run: ./gradlew build

      # 5️⃣ List the build output
      - name: List build output
        run: ls -l build/libs

      # 6️⃣ Log in to Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.USERNAME }}   # Docker Hub username
          password: ${{ secrets.PASSWORD }}      # Docker Hub PAT with Read & Write

      # 7️⃣ Build and push Docker image
      - name: Build and Push Docker Image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: docker.io/manu2041/manu2041docs:latest
